#변수 선언
file:
  directory: D:/SGSG/download/green_gram_jpa

const:
  default-page-size: 20

#MyBatis 설정
mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  issuer: green@green.kr
  secret_key: studyspringbootsagongsugikoreaairforceunivercityyoungjinaaa

# 어플리케이션 설정
spring:
  application:
    name: GreenGramVer3

  #DB 연결 설정
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_jpa
    username: root
    password: green502
  sql:
    init:
      mode: always
  jpa:
    database: mysql
    hibernate:
      #ddl-auto: update #entity가 없으면 create, 기존 존재하는 entity는 컬럼을 새롭게 추가하는 것만 반영
      ddl-auto: create # entity를 서버 기동할 때마다 drop 후 create 한다.
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true # 로그 찍을 때 보기 편하게 포맷함
        order_updates: true # JPA_Batch 작업 활성화
        show_sql: true # JPA가 만든 쿼리문 로그에 출력

  #File 업로드 설정
  servlet:
    multipart:
      max-file-size: 15MB
  jackson:
    default-property-inclusion: non_null #응답 JSON을 만들 때 null인 속성은 제외한다.

#Swagger 설정
springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
